apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: be-keyvault-secrets
  namespace: backend-ns

spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"

    clientID: "71ada0f8-3ea7-41fd-ae42-ce6209a2dfe4"

    keyvaultName: "kvlab123"
    tenantId: "f8aee337-aae4-4a12-8254-683dc276c749"

    objects: |
      array:
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-username
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
