apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}-deployment
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
        {{- if .Values.workloadIdentity.enabled }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: DB_NAME
              value: {{ .Values.env.dbName | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.secretProviderClass.enabled }}
          volumeMounts:
            - name: secrets-store
              mountPath: {{ .Values.secretProviderClass.mountPath | quote }}
              readOnly: true
          {{- end }}
      {{- if .Values.secretProviderClass.enabled }}
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secretProviderClass.name | quote }}
      {{- end }}
