{{- if .Values.secretProviderClass.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    usePodIdentity: {{ .Values.secretProviderClass.usePodIdentity | quote }}
    useVMManagedIdentity: {{ .Values.secretProviderClass.useVMManagedIdentity | quote }}
    clientID: {{ .Values.secretProviderClass.clientId | quote }}
    keyvaultName: {{ .Values.secretProviderClass.keyvaultName | quote }}
    tenantId: {{ .Values.secretProviderClass.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.secretProviderClass.secrets }}
        - |
          objectName: {{ . }}
          objectType: secret
        {{- end }}
{{- end }}
